name: Download Div Image

on:
  workflow_dispatch:

jobs:
  download-div-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install requests Pillow selenium webdriver-manager
      - name: Run Python script
        run: |
          python get_chart.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add div_image.png
          git commit -m "Update date to $(date +%Y-%m-%d)" || echo "No changes to commit"
      - name: Push changes
        run: git push
