name: Make 1v1 elo hist chart

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/1 * * *"

jobs:
  download-div-image:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install requests plotly datetime kaleido pandas
      - name: Run Python script
        run: |
          python img/1v1elochart.py
          python img/tgelochart.py
          python img/mostusedciv.py
          

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add img/Carpincho_1v1elo.png img/dicopatito_1v1elo.png img/Nanox_1v1elo.png img/Carpincho_tgelo.png img/dicopatito_tgelo.png img/Nanox_tgelo.png img/Sir\ Monkey_tgelo.png img/Carpincho_civs.jpg img/dicopatito.jpg img/Nanox_civs.jpg img/Sir\ Monkey_civs.jpg
          git commit -m "Update date to $(date +%Y-%m-%d)" || echo "No changes to commit"
      - name: Push changes
        run: git push
